### ISSUE TITLE
[MOD] FTB

### ISSUE THREAD

**Issue by SpyC0der77** [DM-Earth/Cabricality#185]
### Mod Link

erm

### Propose Reason?

You can just add the ftb mods in the mods folder then export it. It will say "added via overrides" but at least it is already installed

**Comment by KrLite** [comment]
It is NOT OK because most of the FTB mods and some curseforge mods are not permitted to distribute in mod pack formats that are not the curseforge format. We are not stucked with downloading them, we are just stuck with distributing them in our mod pack.

So FTB mods will be replaced in the future, hopefully.

**Comment by SpyC0der77** [comment]
Oh ok. I didn't realize that
