### ISSUE TITLE
redo trading system

### ISSUE THREAD

**Issue by JieningYu** [DM-Earth/Cabricality#73]

**Comment by IcedDog** [comment]
okay im done with my part, all the basic essential codes are redone and i really dont have much time to work on this
there's still a few problems that needs you guys to iron out but im sure it wont take much time
1. missing item and item display name in trade cards (you can identify block or item by looking at the entry_cost varible, -10 is block and 10 is item), some of them are mysteriously recoginzed as air
2. trader machine recipe does not seem to work, but the basic structure is there and probably shouldnt cause too much problem
3. lang file sync
4. the new quest page are not translated and fully checked, make sure to export the DATAGEN in the startup script to generate the Shipment page (i did not do this since we might be adding things later)

**Comment by JieningYu** [comment]
for 1 and 3, I will try to use Cabfu to register these cards.

**Comment by JieningYu** [comment]
Current state: redoing trading with cabfu

**Comment by IcedDog** [comment]
i love you
